"""
management/commands/seed_exercises.py

Run with:
    python manage.py seed_exercises

Creates the global exercise library. Safe to re-run — uses
get_or_create so existing exercises are never duplicated.
"""

from django.core.management.base import BaseCommand
from workout.models import Exercise, MuscleGroup, EquipmentType, ExerciseType, DifficultyLevel

EXERCISES = [

    # ──────────────────────────────────────────────────────────────
    # CHEST
    # ──────────────────────────────────────────────────────────────
    {
        "name": "Barbell Bench Press",
        "muscle_group": MuscleGroup.CHEST,
        "secondary_muscles": ["triceps", "shoulders"],
        "equipment": EquipmentType.BARBELL,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.INTERMEDIATE,
        "instructions": "Lie flat on a bench. Grip the bar just outside shoulder width. Lower the bar to your mid-chest with control, then press back up to full extension.",
        "tips": "Keep shoulder blades pinched and retracted. Drive feet into the floor. Avoid bouncing the bar off your chest.",
    },
    {
        "name": "Incline Barbell Bench Press",
        "muscle_group": MuscleGroup.CHEST,
        "secondary_muscles": ["triceps", "shoulders"],
        "equipment": EquipmentType.BARBELL,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.INTERMEDIATE,
        "instructions": "Set the bench to 30–45°. Press the bar from the upper chest upward. Control the descent.",
        "tips": "Angle emphasizes the upper chest. Avoid flaring elbows too wide.",
    },
    {
        "name": "Decline Barbell Bench Press",
        "muscle_group": MuscleGroup.CHEST,
        "secondary_muscles": ["triceps"],
        "equipment": EquipmentType.BARBELL,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.INTERMEDIATE,
        "instructions": "Set bench to a 15–30° decline. Lower bar to lower chest and press up.",
        "tips": "Targets the lower chest. Ensure feet are secured before starting.",
    },
    {
        "name": "Dumbbell Bench Press",
        "muscle_group": MuscleGroup.CHEST,
        "secondary_muscles": ["triceps", "shoulders"],
        "equipment": EquipmentType.DUMBBELL,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Lie flat on bench with a dumbbell in each hand at chest level. Press up and together, then lower with control.",
        "tips": "Greater range of motion than barbell. Keep a neutral wrist throughout.",
    },
    {
        "name": "Incline Dumbbell Press",
        "muscle_group": MuscleGroup.CHEST,
        "secondary_muscles": ["triceps", "shoulders"],
        "equipment": EquipmentType.DUMBBELL,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Set bench to 30–45°. Press dumbbells from shoulder height upward and together.",
        "tips": "Focus on squeezing the upper chest at the top.",
    },
    {
        "name": "Dumbbell Fly",
        "muscle_group": MuscleGroup.CHEST,
        "secondary_muscles": [],
        "equipment": EquipmentType.DUMBBELL,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Lie flat with arms extended above chest, slight bend in elbows. Lower arms out wide in an arc, then bring them back together.",
        "tips": "Keep elbows slightly bent throughout. Feel the stretch in your chest at the bottom.",
    },
    {
        "name": "Cable Chest Fly",
        "muscle_group": MuscleGroup.CHEST,
        "secondary_muscles": [],
        "equipment": EquipmentType.CABLE,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Set cables to chest height. Stand in the middle, pull handles together in a hugging motion.",
        "tips": "Constant tension throughout the movement. Squeeze at the peak contraction.",
    },
    {
        "name": "High-to-Low Cable Fly",
        "muscle_group": MuscleGroup.CHEST,
        "secondary_muscles": [],
        "equipment": EquipmentType.CABLE,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Set cables high. Pull handles downward and together in front of your lower chest.",
        "tips": "Targets the lower chest. Lean slightly forward for better angle.",
    },
    {
        "name": "Push-Up",
        "muscle_group": MuscleGroup.CHEST,
        "secondary_muscles": ["triceps", "core", "shoulders"],
        "equipment": EquipmentType.BODYWEIGHT,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Start in a plank with hands slightly outside shoulder width. Lower chest to the floor, then push back up.",
        "tips": "Keep body in a straight line. Don't let your hips sag or pike up.",
    },
    {
        "name": "Decline Push-Up",
        "muscle_group": MuscleGroup.CHEST,
        "secondary_muscles": ["triceps", "shoulders"],
        "equipment": EquipmentType.BODYWEIGHT,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.INTERMEDIATE,
        "instructions": "Place feet on an elevated surface. Perform a push-up with hands on the floor.",
        "tips": "Elevating feet shifts focus to the upper chest.",
    },
    {
        "name": "Chest Dip",
        "muscle_group": MuscleGroup.CHEST,
        "secondary_muscles": ["triceps", "shoulders"],
        "equipment": EquipmentType.BODYWEIGHT,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.INTERMEDIATE,
        "instructions": "Lean forward on parallel bars. Lower until elbows reach 90°, then press back up.",
        "tips": "Lean forward to emphasize chest over triceps.",
    },
    {
        "name": "Machine Chest Press",
        "muscle_group": MuscleGroup.CHEST,
        "secondary_muscles": ["triceps", "shoulders"],
        "equipment": EquipmentType.MACHINE,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Sit in machine, adjust seat so handles are at chest level. Press handles forward to full extension.",
        "tips": "Good for beginners or as a burnout finisher. Controlled negative.",
    },
    {
        "name": "Pec Deck Machine",
        "muscle_group": MuscleGroup.CHEST,
        "secondary_muscles": [],
        "equipment": EquipmentType.MACHINE,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Sit upright. Place forearms on pads. Bring pads together in front of chest.",
        "tips": "Isolates the chest. Great as a finishing exercise.",
    },

    # ──────────────────────────────────────────────────────────────
    # BACK
    # ──────────────────────────────────────────────────────────────
    {
        "name": "Deadlift",
        "muscle_group": MuscleGroup.BACK,
        "secondary_muscles": ["glutes", "hamstrings", "core", "forearms"],
        "equipment": EquipmentType.BARBELL,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.ADVANCED,
        "instructions": "Stand with feet hip-width apart, bar over mid-foot. Hinge at hips, grip the bar. Drive through heels and extend hips and knees simultaneously to stand tall.",
        "tips": "Keep bar close to the body at all times. Neutral spine is critical. Brace your core before pulling.",
    },
    {
        "name": "Romanian Deadlift",
        "muscle_group": MuscleGroup.BACK,
        "secondary_muscles": ["hamstrings", "glutes"],
        "equipment": EquipmentType.BARBELL,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.INTERMEDIATE,
        "instructions": "Hold bar at hip level. Push hips back while lowering bar along thighs. Feel a stretch in hamstrings. Drive hips forward to return.",
        "tips": "Soft bend in knees. Don't round the lower back.",
    },
    {
        "name": "Bent-Over Barbell Row",
        "muscle_group": MuscleGroup.BACK,
        "secondary_muscles": ["biceps", "rear delts", "core"],
        "equipment": EquipmentType.BARBELL,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.INTERMEDIATE,
        "instructions": "Hinge forward to about 45°. Pull bar toward lower chest/upper abdomen. Squeeze shoulder blades at top.",
        "tips": "Keep back flat. Don't use momentum. Lead with elbows.",
    },
    {
        "name": "Pendlay Row",
        "muscle_group": MuscleGroup.BACK,
        "secondary_muscles": ["biceps", "core"],
        "equipment": EquipmentType.BARBELL,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.INTERMEDIATE,
        "instructions": "Bar starts on floor each rep. Torso parallel to ground. Explosively row bar to lower chest. Return to floor with control.",
        "tips": "More strict than a regular row. Builds explosive back strength.",
    },
    {
        "name": "Pull-Up",
        "muscle_group": MuscleGroup.BACK,
        "secondary_muscles": ["biceps", "core"],
        "equipment": EquipmentType.BODYWEIGHT,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.INTERMEDIATE,
        "instructions": "Hang from bar with overhand grip slightly outside shoulder width. Pull chest to bar, then lower with control.",
        "tips": "Full range of motion — start from dead hang. Avoid kipping.",
    },
    {
        "name": "Chin-Up",
        "muscle_group": MuscleGroup.BACK,
        "secondary_muscles": ["biceps"],
        "equipment": EquipmentType.BODYWEIGHT,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.INTERMEDIATE,
        "instructions": "Hang with underhand grip, shoulder width. Pull chin above bar, lower with control.",
        "tips": "Underhand grip increases bicep involvement.",
    },
    {
        "name": "Lat Pulldown",
        "muscle_group": MuscleGroup.BACK,
        "secondary_muscles": ["biceps"],
        "equipment": EquipmentType.CABLE,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Grip bar wide, sit down with thighs under pads. Pull bar to upper chest while leaning slightly back.",
        "tips": "Drive elbows down and back. Avoid using momentum.",
    },
    {
        "name": "Single-Arm Dumbbell Row",
        "muscle_group": MuscleGroup.BACK,
        "secondary_muscles": ["biceps", "rear delts"],
        "equipment": EquipmentType.DUMBBELL,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Place one hand and knee on bench. Row dumbbell to hip with opposite arm, keeping back flat.",
        "tips": "Drive elbow back, not up. Full stretch at bottom.",
    },
    {
        "name": "Seated Cable Row",
        "muscle_group": MuscleGroup.BACK,
        "secondary_muscles": ["biceps", "rear delts"],
        "equipment": EquipmentType.CABLE,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Sit at cable row station. Pull handle to your abdomen while keeping back upright and chest out.",
        "tips": "Don't lean too far back. Squeeze shoulder blades together at the end.",
    },
    {
        "name": "T-Bar Row",
        "muscle_group": MuscleGroup.BACK,
        "secondary_muscles": ["biceps", "rear delts"],
        "equipment": EquipmentType.BARBELL,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.INTERMEDIATE,
        "instructions": "Straddle the bar, grip the handle. Hinge to roughly 45°. Row the bar to chest.",
        "tips": "Keep chest pressed against pad if using machine variant.",
    },
    {
        "name": "Cable Straight-Arm Pulldown",
        "muscle_group": MuscleGroup.BACK,
        "secondary_muscles": [],
        "equipment": EquipmentType.CABLE,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Stand facing high cable. Arms extended, pull rope/bar down to hips in an arc keeping arms straight.",
        "tips": "Isolates the lats. Great as a lat activation exercise.",
    },
    {
        "name": "Face Pull",
        "muscle_group": MuscleGroup.BACK,
        "secondary_muscles": ["rear delts", "rotator cuff"],
        "equipment": EquipmentType.CABLE,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Set cable to eye level with rope attachment. Pull toward your face, flaring elbows out.",
        "tips": "Essential for shoulder health. Keep upper arms parallel to floor.",
    },
    {
        "name": "Hyperextension (Back Extension)",
        "muscle_group": MuscleGroup.BACK,
        "secondary_muscles": ["glutes", "hamstrings"],
        "equipment": EquipmentType.MACHINE,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Lie face down on the machine. Lower torso toward floor, then raise back to parallel.",
        "tips": "Squeeze glutes at the top. Can add weight for progression.",
    },

    # ──────────────────────────────────────────────────────────────
    # SHOULDERS
    # ──────────────────────────────────────────────────────────────
    {
        "name": "Overhead Press (Barbell)",
        "muscle_group": MuscleGroup.SHOULDERS,
        "secondary_muscles": ["triceps", "core"],
        "equipment": EquipmentType.BARBELL,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.INTERMEDIATE,
        "instructions": "Stand with bar at collarbone level. Press straight up overhead to full elbow extension. Lower with control.",
        "tips": "Brace core tight. Don't hyperextend lower back. Keep bar path vertical.",
    },
    {
        "name": "Seated Dumbbell Shoulder Press",
        "muscle_group": MuscleGroup.SHOULDERS,
        "secondary_muscles": ["triceps"],
        "equipment": EquipmentType.DUMBBELL,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Sit on a bench with back support. Hold dumbbells at ear level. Press overhead.",
        "tips": "Back support reduces lower back strain.",
    },
    {
        "name": "Dumbbell Lateral Raise",
        "muscle_group": MuscleGroup.SHOULDERS,
        "secondary_muscles": [],
        "equipment": EquipmentType.DUMBBELL,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Stand with dumbbells at sides. Raise arms out to the side to shoulder height with slight bend in elbows.",
        "tips": "Lead with elbows, not hands. Avoid shrugging. Use lighter weight.",
    },
    {
        "name": "Cable Lateral Raise",
        "muscle_group": MuscleGroup.SHOULDERS,
        "secondary_muscles": [],
        "equipment": EquipmentType.CABLE,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Set cable to lowest point. Raise arm out to the side to shoulder height.",
        "tips": "Cable provides constant tension unlike dumbbells.",
    },
    {
        "name": "Front Raise",
        "muscle_group": MuscleGroup.SHOULDERS,
        "secondary_muscles": [],
        "equipment": EquipmentType.DUMBBELL,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Hold dumbbells in front of thighs. Raise both arms forward to shoulder height.",
        "tips": "Targets anterior deltoid. Don't lean back.",
    },
    {
        "name": "Arnold Press",
        "muscle_group": MuscleGroup.SHOULDERS,
        "secondary_muscles": ["triceps"],
        "equipment": EquipmentType.DUMBBELL,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.INTERMEDIATE,
        "instructions": "Start with dumbbells in front at chin, palms facing you. Rotate palms outward as you press up.",
        "tips": "Hits all three delt heads. Slower tempo for best results.",
    },
    {
        "name": "Upright Row",
        "muscle_group": MuscleGroup.SHOULDERS,
        "secondary_muscles": ["biceps", "traps"],
        "equipment": EquipmentType.BARBELL,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.INTERMEDIATE,
        "instructions": "Hold bar with narrow overhand grip. Pull bar straight up to chin, leading with elbows.",
        "tips": "Wide grip reduces impingement risk. Avoid if you have shoulder issues.",
    },
    {
        "name": "Machine Shoulder Press",
        "muscle_group": MuscleGroup.SHOULDERS,
        "secondary_muscles": ["triceps"],
        "equipment": EquipmentType.MACHINE,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Sit in machine, adjust handles to shoulder height. Press up to full extension.",
        "tips": "Safer for beginners or when fatigued.",
    },
    {
        "name": "Barbell Shrug",
        "muscle_group": MuscleGroup.SHOULDERS,
        "secondary_muscles": [],
        "equipment": EquipmentType.BARBELL,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Hold barbell at hip level. Shrug shoulders straight up toward ears. Hold briefly, then lower.",
        "tips": "Targets the upper traps. Don't roll shoulders.",
    },

    # ──────────────────────────────────────────────────────────────
    # BICEPS
    # ──────────────────────────────────────────────────────────────
    {
        "name": "Barbell Curl",
        "muscle_group": MuscleGroup.BICEPS,
        "secondary_muscles": ["forearms"],
        "equipment": EquipmentType.BARBELL,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Stand with bar at hip level, underhand grip. Curl bar to shoulder height. Lower with control.",
        "tips": "Keep elbows fixed at sides. Avoid swinging.",
    },
    {
        "name": "EZ-Bar Curl",
        "muscle_group": MuscleGroup.BICEPS,
        "secondary_muscles": ["forearms"],
        "equipment": EquipmentType.BARBELL,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Use EZ-bar with semi-supinated grip. Curl to shoulder height.",
        "tips": "Easier on the wrists than straight barbell.",
    },
    {
        "name": "Dumbbell Bicep Curl",
        "muscle_group": MuscleGroup.BICEPS,
        "secondary_muscles": ["forearms"],
        "equipment": EquipmentType.DUMBBELL,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Hold dumbbells at sides, supinate wrists as you curl up. Alternate or both together.",
        "tips": "Supination (rotating palm up) maximizes bicep activation.",
    },
    {
        "name": "Hammer Curl",
        "muscle_group": MuscleGroup.BICEPS,
        "secondary_muscles": ["forearms", "brachialis"],
        "equipment": EquipmentType.DUMBBELL,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Hold dumbbells with neutral grip (palms facing each other). Curl up without rotating wrist.",
        "tips": "Targets brachialis and brachioradialis. Builds arm thickness.",
    },
    {
        "name": "Incline Dumbbell Curl",
        "muscle_group": MuscleGroup.BICEPS,
        "secondary_muscles": [],
        "equipment": EquipmentType.DUMBBELL,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Lie back on an incline bench, arms hanging straight. Curl dumbbells up.",
        "tips": "Stretched starting position increases range of motion and long head activation.",
    },
    {
        "name": "Cable Curl",
        "muscle_group": MuscleGroup.BICEPS,
        "secondary_muscles": [],
        "equipment": EquipmentType.CABLE,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Stand facing low cable. Curl bar or rope to shoulder height.",
        "tips": "Constant tension through full range of motion.",
    },
    {
        "name": "Concentration Curl",
        "muscle_group": MuscleGroup.BICEPS,
        "secondary_muscles": [],
        "equipment": EquipmentType.DUMBBELL,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Sit on bench, elbow braced against inner thigh. Curl dumbbell upward.",
        "tips": "Isolates the bicep. Great for peak contraction.",
    },
    {
        "name": "Preacher Curl",
        "muscle_group": MuscleGroup.BICEPS,
        "secondary_muscles": [],
        "equipment": EquipmentType.MACHINE,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Rest upper arms on preacher pad. Curl bar or dumbbell upward.",
        "tips": "Eliminates cheating. Emphasizes short head of bicep.",
    },

    # ──────────────────────────────────────────────────────────────
    # TRICEPS
    # ──────────────────────────────────────────────────────────────
    {
        "name": "Close-Grip Bench Press",
        "muscle_group": MuscleGroup.TRICEPS,
        "secondary_muscles": ["chest", "shoulders"],
        "equipment": EquipmentType.BARBELL,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.INTERMEDIATE,
        "instructions": "Lie on bench. Grip bar with hands shoulder-width or slightly inside. Lower bar to chest, press back up.",
        "tips": "Keep elbows tucked to sides to maximize tricep engagement.",
    },
    {
        "name": "Tricep Pushdown (Cable)",
        "muscle_group": MuscleGroup.TRICEPS,
        "secondary_muscles": [],
        "equipment": EquipmentType.CABLE,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Set cable to high position with bar or rope. Push handle down to full elbow extension. Control the return.",
        "tips": "Keep elbows locked at sides. Full extension at bottom.",
    },
    {
        "name": "Overhead Tricep Extension (Dumbbell)",
        "muscle_group": MuscleGroup.TRICEPS,
        "secondary_muscles": [],
        "equipment": EquipmentType.DUMBBELL,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Hold one dumbbell with both hands overhead. Lower behind head by bending elbows, then extend back up.",
        "tips": "Stretches the long head of tricep. Don't flare elbows.",
    },
    {
        "name": "Overhead Tricep Extension (Cable)",
        "muscle_group": MuscleGroup.TRICEPS,
        "secondary_muscles": [],
        "equipment": EquipmentType.CABLE,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Face away from low cable. Hold rope overhead and extend arms forward.",
        "tips": "Long head stretch under tension.",
    },
    {
        "name": "Skull Crusher",
        "muscle_group": MuscleGroup.TRICEPS,
        "secondary_muscles": [],
        "equipment": EquipmentType.BARBELL,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.INTERMEDIATE,
        "instructions": "Lie on bench. Hold EZ-bar above chest with straight arms. Lower toward forehead by bending elbows, then extend.",
        "tips": "Go slow on the negative. Use EZ-bar to reduce wrist strain.",
    },
    {
        "name": "Tricep Dip",
        "muscle_group": MuscleGroup.TRICEPS,
        "secondary_muscles": ["chest", "shoulders"],
        "equipment": EquipmentType.BODYWEIGHT,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.INTERMEDIATE,
        "instructions": "Grip parallel bars, body upright. Lower until elbows hit 90°, then press back up.",
        "tips": "Stay more upright to hit triceps more than chest.",
    },
    {
        "name": "Bench Dip",
        "muscle_group": MuscleGroup.TRICEPS,
        "secondary_muscles": [],
        "equipment": EquipmentType.BODYWEIGHT,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Place hands on bench edge behind you, feet on floor. Lower body by bending elbows, then push back up.",
        "tips": "Beginner-friendly. Add weight on lap for progression.",
    },
    {
        "name": "Diamond Push-Up",
        "muscle_group": MuscleGroup.TRICEPS,
        "secondary_muscles": ["chest"],
        "equipment": EquipmentType.BODYWEIGHT,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.INTERMEDIATE,
        "instructions": "Form a diamond shape with hands directly under chest. Perform push-up.",
        "tips": "Maximizes tricep and inner chest activation.",
    },

    # ──────────────────────────────────────────────────────────────
    # FOREARMS
    # ──────────────────────────────────────────────────────────────
    {
        "name": "Wrist Curl",
        "muscle_group": MuscleGroup.FOREARMS,
        "secondary_muscles": [],
        "equipment": EquipmentType.BARBELL,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Sit with forearms resting on thighs, palms up. Curl wrists upward.",
        "tips": "Full range of motion. Don't rush the movement.",
    },
    {
        "name": "Reverse Wrist Curl",
        "muscle_group": MuscleGroup.FOREARMS,
        "secondary_muscles": [],
        "equipment": EquipmentType.BARBELL,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Sit with forearms on thighs, palms down. Curl wrists upward.",
        "tips": "Targets extensor muscles on the back of the forearm.",
    },
    {
        "name": "Farmer's Walk",
        "muscle_group": MuscleGroup.FOREARMS,
        "secondary_muscles": ["core", "traps", "glutes"],
        "equipment": EquipmentType.DUMBBELL,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Hold heavy dumbbells at sides. Walk a set distance or time maintaining upright posture.",
        "tips": "Builds grip strength and overall conditioning. Keep core tight.",
    },
    {
        "name": "Dead Hang",
        "muscle_group": MuscleGroup.FOREARMS,
        "secondary_muscles": ["back", "core"],
        "equipment": EquipmentType.BODYWEIGHT,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Hang from a pull-up bar with straight arms. Hold for time.",
        "tips": "Excellent for grip and shoulder health. Progress duration over time.",
    },

    # ──────────────────────────────────────────────────────────────
    # CORE
    # ──────────────────────────────────────────────────────────────
    {
        "name": "Plank",
        "muscle_group": MuscleGroup.CORE,
        "secondary_muscles": ["shoulders", "glutes"],
        "equipment": EquipmentType.BODYWEIGHT,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Hold a push-up position on forearms. Keep body in a straight line. Hold for time.",
        "tips": "Don't let hips sag or rise. Breathe steadily.",
    },
    {
        "name": "Side Plank",
        "muscle_group": MuscleGroup.CORE,
        "secondary_muscles": ["glutes"],
        "equipment": EquipmentType.BODYWEIGHT,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Support body on one forearm and the side of your foot. Keep body straight.",
        "tips": "Targets the obliques. Don't let hips drop.",
    },
    {
        "name": "Crunch",
        "muscle_group": MuscleGroup.CORE,
        "secondary_muscles": [],
        "equipment": EquipmentType.BODYWEIGHT,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Lie on back, knees bent. Curl shoulders toward knees. Lower with control.",
        "tips": "Short range of motion. Focus on contracting the abs.",
    },
    {
        "name": "Bicycle Crunch",
        "muscle_group": MuscleGroup.CORE,
        "secondary_muscles": [],
        "equipment": EquipmentType.BODYWEIGHT,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Lie on back, hands behind head. Alternate bringing opposite elbow to knee in a pedaling motion.",
        "tips": "Controlled rotation. Don't pull on the neck.",
    },
    {
        "name": "Leg Raise",
        "muscle_group": MuscleGroup.CORE,
        "secondary_muscles": ["hip flexors"],
        "equipment": EquipmentType.BODYWEIGHT,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Lie flat. Raise straight legs to 90°. Lower slowly without touching the floor.",
        "tips": "Press lower back into floor to protect it.",
    },
    {
        "name": "Hanging Leg Raise",
        "muscle_group": MuscleGroup.CORE,
        "secondary_muscles": ["hip flexors", "forearms"],
        "equipment": EquipmentType.BODYWEIGHT,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.INTERMEDIATE,
        "instructions": "Hang from pull-up bar. Raise legs to 90° or higher. Lower with control.",
        "tips": "Avoid swinging. Can progress to toes-to-bar.",
    },
    {
        "name": "Cable Crunch",
        "muscle_group": MuscleGroup.CORE,
        "secondary_muscles": [],
        "equipment": EquipmentType.CABLE,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Kneel at cable machine with rope overhead. Crunch elbows toward knees.",
        "tips": "Allows progressive overload for abs unlike bodyweight crunches.",
    },
    {
        "name": "Ab Wheel Rollout",
        "muscle_group": MuscleGroup.CORE,
        "secondary_muscles": ["shoulders", "lats"],
        "equipment": EquipmentType.OTHER,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.ADVANCED,
        "instructions": "Kneel holding ab wheel. Roll forward until body is parallel to floor. Roll back using core.",
        "tips": "Very challenging. Start with partial range of motion.",
    },
    {
        "name": "Russian Twist",
        "muscle_group": MuscleGroup.CORE,
        "secondary_muscles": [],
        "equipment": EquipmentType.BODYWEIGHT,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Sit with feet off floor, lean back slightly. Rotate torso side to side.",
        "tips": "Add weight for progression. Keep feet elevated for more difficulty.",
    },
    {
        "name": "Dead Bug",
        "muscle_group": MuscleGroup.CORE,
        "secondary_muscles": [],
        "equipment": EquipmentType.BODYWEIGHT,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Lie on back, arms up, knees at 90°. Extend opposite arm and leg simultaneously while pressing back into floor.",
        "tips": "Excellent for core stability. Move slowly and controlled.",
    },

    # ──────────────────────────────────────────────────────────────
    # QUADS
    # ──────────────────────────────────────────────────────────────
    {
        "name": "Barbell Back Squat",
        "muscle_group": MuscleGroup.QUADS,
        "secondary_muscles": ["glutes", "hamstrings", "core"],
        "equipment": EquipmentType.BARBELL,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.INTERMEDIATE,
        "instructions": "Bar on upper traps. Feet shoulder-width. Squat until thighs are parallel to floor. Drive through heels to stand.",
        "tips": "Knees track over toes. Keep chest up. Brace core before descending.",
    },
    {
        "name": "Front Squat",
        "muscle_group": MuscleGroup.QUADS,
        "secondary_muscles": ["core", "glutes"],
        "equipment": EquipmentType.BARBELL,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.ADVANCED,
        "instructions": "Bar rests on front delts. Elbows high. Squat to depth, maintaining upright torso.",
        "tips": "Requires wrist flexibility. More quad-dominant than back squat.",
    },
    {
        "name": "Goblet Squat",
        "muscle_group": MuscleGroup.QUADS,
        "secondary_muscles": ["glutes", "core"],
        "equipment": EquipmentType.DUMBBELL,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Hold dumbbell vertically at chest. Squat down between your arms.",
        "tips": "Great for teaching squat mechanics. Upright torso naturally achieved.",
    },
    {
        "name": "Leg Press",
        "muscle_group": MuscleGroup.QUADS,
        "secondary_muscles": ["glutes", "hamstrings"],
        "equipment": EquipmentType.MACHINE,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Sit in machine, feet on plate shoulder-width. Push plate up, lower until knees at 90°.",
        "tips": "Don't lock out knees. Foot placement changes muscle emphasis.",
    },
    {
        "name": "Leg Extension",
        "muscle_group": MuscleGroup.QUADS,
        "secondary_muscles": [],
        "equipment": EquipmentType.MACHINE,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Sit in leg extension machine. Extend knees fully. Lower with control.",
        "tips": "Quad isolation. Control the negative for maximum activation.",
    },
    {
        "name": "Hack Squat",
        "muscle_group": MuscleGroup.QUADS,
        "secondary_muscles": ["glutes"],
        "equipment": EquipmentType.MACHINE,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.INTERMEDIATE,
        "instructions": "Position on hack squat machine. Lower to 90° or below. Push through heels.",
        "tips": "Lower foot placement increases quad focus.",
    },
    {
        "name": "Bulgarian Split Squat",
        "muscle_group": MuscleGroup.QUADS,
        "secondary_muscles": ["glutes", "hamstrings"],
        "equipment": EquipmentType.DUMBBELL,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.INTERMEDIATE,
        "instructions": "Rear foot elevated on bench. Lower front knee toward ground. Push back up through front heel.",
        "tips": "Excellent single-leg strength builder. Keep torso upright.",
    },
    {
        "name": "Walking Lunge",
        "muscle_group": MuscleGroup.QUADS,
        "secondary_muscles": ["glutes", "hamstrings"],
        "equipment": EquipmentType.DUMBBELL,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Step forward into a lunge, lower back knee to floor. Bring rear foot forward and repeat.",
        "tips": "Keep torso upright. Large step for glutes, smaller for quads.",
    },
    {
        "name": "Step-Up",
        "muscle_group": MuscleGroup.QUADS,
        "secondary_muscles": ["glutes"],
        "equipment": EquipmentType.DUMBBELL,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Hold dumbbells. Step onto a bench or box. Bring trailing foot up. Step back down.",
        "tips": "Drive through the heel of the stepping foot.",
    },

    # ──────────────────────────────────────────────────────────────
    # HAMSTRINGS
    # ──────────────────────────────────────────────────────────────
    {
        "name": "Lying Leg Curl",
        "muscle_group": MuscleGroup.HAMSTRINGS,
        "secondary_muscles": [],
        "equipment": EquipmentType.MACHINE,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Lie face down on leg curl machine. Curl legs toward glutes. Lower with control.",
        "tips": "Squeeze hamstrings at peak. Avoid lifting hips.",
    },
    {
        "name": "Seated Leg Curl",
        "muscle_group": MuscleGroup.HAMSTRINGS,
        "secondary_muscles": [],
        "equipment": EquipmentType.MACHINE,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Sit in machine. Curl legs under the pad. Return to start with control.",
        "tips": "Seated position stretches hamstrings more than lying.",
    },
    {
        "name": "Nordic Hamstring Curl",
        "muscle_group": MuscleGroup.HAMSTRINGS,
        "secondary_muscles": ["glutes"],
        "equipment": EquipmentType.BODYWEIGHT,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.ADVANCED,
        "instructions": "Kneel with feet anchored. Lower your body slowly toward the floor using hamstrings. Use hands to catch yourself. Return up.",
        "tips": "One of the most effective hamstring exercises. Very difficult — start with eccentrics only.",
    },
    {
        "name": "Good Morning",
        "muscle_group": MuscleGroup.HAMSTRINGS,
        "secondary_muscles": ["lower back", "glutes"],
        "equipment": EquipmentType.BARBELL,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.INTERMEDIATE,
        "instructions": "Bar on upper traps. Hinge at hips, pushing them back. Lower torso until parallel to floor. Drive hips forward to stand.",
        "tips": "Keep back neutral. Soft bend in knees. Heavy loading demands great technique.",
    },
    {
        "name": "Dumbbell Romanian Deadlift",
        "muscle_group": MuscleGroup.HAMSTRINGS,
        "secondary_muscles": ["glutes", "lower back"],
        "equipment": EquipmentType.DUMBBELL,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Hold dumbbells in front of thighs. Hinge at hips, lowering dumbbells along legs. Feel hamstring stretch. Return to standing.",
        "tips": "Easier to learn than barbell RDL. Great for beginners.",
    },

    # ──────────────────────────────────────────────────────────────
    # GLUTES
    # ──────────────────────────────────────────────────────────────
    {
        "name": "Barbell Hip Thrust",
        "muscle_group": MuscleGroup.GLUTES,
        "secondary_muscles": ["hamstrings", "core"],
        "equipment": EquipmentType.BARBELL,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.INTERMEDIATE,
        "instructions": "Upper back on bench, bar over hips. Drive hips up until body is parallel. Squeeze glutes at top.",
        "tips": "The gold standard for glute development. Use a pad on the bar.",
    },
    {
        "name": "Glute Bridge",
        "muscle_group": MuscleGroup.GLUTES,
        "secondary_muscles": ["hamstrings", "core"],
        "equipment": EquipmentType.BODYWEIGHT,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Lie on back, knees bent. Drive hips up by squeezing glutes. Lower with control.",
        "tips": "Beginner version of hip thrust. Add weight on hips to progress.",
    },
    {
        "name": "Cable Kickback",
        "muscle_group": MuscleGroup.GLUTES,
        "secondary_muscles": ["hamstrings"],
        "equipment": EquipmentType.CABLE,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Attach ankle strap to low cable. Kick leg back and up, squeezing glute at top.",
        "tips": "Keep torso stable. Full squeeze at peak.",
    },
    {
        "name": "Sumo Deadlift",
        "muscle_group": MuscleGroup.GLUTES,
        "secondary_muscles": ["hamstrings", "quads", "back"],
        "equipment": EquipmentType.BARBELL,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.INTERMEDIATE,
        "instructions": "Wide stance, toes pointed out. Grip bar between legs. Pull bar up, driving hips forward.",
        "tips": "More glute and inner thigh emphasis than conventional deadlift.",
    },
    {
        "name": "Donkey Kick",
        "muscle_group": MuscleGroup.GLUTES,
        "secondary_muscles": [],
        "equipment": EquipmentType.BODYWEIGHT,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "On hands and knees. Kick one leg up toward ceiling, keeping knee bent. Squeeze glute at top.",
        "tips": "Bodyweight isolation for glutes. Add ankle weights for progression.",
    },

    # ──────────────────────────────────────────────────────────────
    # CALVES
    # ──────────────────────────────────────────────────────────────
    {
        "name": "Standing Calf Raise",
        "muscle_group": MuscleGroup.CALVES,
        "secondary_muscles": [],
        "equipment": EquipmentType.MACHINE,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Stand on calf raise machine. Rise onto toes as high as possible. Lower below platform level.",
        "tips": "Full range of motion is key — deep stretch at bottom, full contraction at top.",
    },
    {
        "name": "Seated Calf Raise",
        "muscle_group": MuscleGroup.CALVES,
        "secondary_muscles": [],
        "equipment": EquipmentType.MACHINE,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Sit with knees under pad. Rise onto toes. Lower with control.",
        "tips": "Targets soleus more than standing variation.",
    },
    {
        "name": "Donkey Calf Raise",
        "muscle_group": MuscleGroup.CALVES,
        "secondary_muscles": [],
        "equipment": EquipmentType.BODYWEIGHT,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Hinge forward, balls of feet on edge. Rise onto toes. Lower for full stretch.",
        "tips": "Hip flexion changes angle and stretches the gastrocnemius more.",
    },
    {
        "name": "Single-Leg Calf Raise",
        "muscle_group": MuscleGroup.CALVES,
        "secondary_muscles": [],
        "equipment": EquipmentType.BODYWEIGHT,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Balance on one foot on a step edge. Rise onto toes. Lower for full stretch.",
        "tips": "Hold a dumbbell for added resistance.",
    },

    # ──────────────────────────────────────────────────────────────
    # CARDIO
    # ──────────────────────────────────────────────────────────────
    {
        "name": "Treadmill Run",
        "muscle_group": MuscleGroup.CARDIO,
        "secondary_muscles": ["quads", "hamstrings", "calves"],
        "equipment": EquipmentType.MACHINE,
        "exercise_type": ExerciseType.CARDIO,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Set desired speed and incline. Maintain upright posture. Swing arms naturally.",
        "tips": "Tracked in duration/distance rather than sets/reps.",
    },
    {
        "name": "Stationary Bike",
        "muscle_group": MuscleGroup.CARDIO,
        "secondary_muscles": ["quads", "calves"],
        "equipment": EquipmentType.MACHINE,
        "exercise_type": ExerciseType.CARDIO,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Adjust seat height. Pedal at target RPM/resistance for duration.",
        "tips": "Low impact. Great for active recovery days.",
    },
    {
        "name": "Rowing Machine",
        "muscle_group": MuscleGroup.CARDIO,
        "secondary_muscles": ["back", "biceps", "legs"],
        "equipment": EquipmentType.MACHINE,
        "exercise_type": ExerciseType.CARDIO,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Drive with legs first, then lean back, then pull handle to lower chest. Reverse the sequence to return.",
        "tips": "60% legs, 20% back, 20% arms. Great full-body cardio.",
    },
    {
        "name": "Jump Rope",
        "muscle_group": MuscleGroup.CARDIO,
        "secondary_muscles": ["calves", "shoulders"],
        "equipment": EquipmentType.OTHER,
        "exercise_type": ExerciseType.CARDIO,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Jump at a consistent rhythm. Land softly on the balls of your feet.",
        "tips": "Excellent warm-up or conditioning tool. Progress to double-unders.",
    },
    {
        "name": "Burpee",
        "muscle_group": MuscleGroup.CARDIO,
        "secondary_muscles": ["chest", "quads", "shoulders", "core"],
        "equipment": EquipmentType.BODYWEIGHT,
        "exercise_type": ExerciseType.PLYOMETRIC,
        "difficulty": DifficultyLevel.INTERMEDIATE,
        "instructions": "Drop to a push-up position, perform push-up, jump feet in, then explode up with a jump.",
        "tips": "Full body conditioning. Modify by removing the jump if needed.",
    },
    {
        "name": "Box Jump",
        "muscle_group": MuscleGroup.CARDIO,
        "secondary_muscles": ["quads", "glutes", "calves"],
        "equipment": EquipmentType.OTHER,
        "exercise_type": ExerciseType.PLYOMETRIC,
        "difficulty": DifficultyLevel.INTERMEDIATE,
        "instructions": "Stand in front of a box. Dip into a quarter squat and explode onto the box. Step or jump back down.",
        "tips": "Land softly with knees bent. Always step down — don't jump down from height.",
    },
    {
        "name": "Battle Ropes",
        "muscle_group": MuscleGroup.CARDIO,
        "secondary_muscles": ["shoulders", "core", "forearms"],
        "equipment": EquipmentType.OTHER,
        "exercise_type": ExerciseType.CARDIO,
        "difficulty": DifficultyLevel.INTERMEDIATE,
        "instructions": "Hold one rope in each hand. Alternate or simultaneously slam ropes in waves.",
        "tips": "High-intensity conditioning. Keep knees slightly bent throughout.",
    },

    # ──────────────────────────────────────────────────────────────
    # FULL BODY / COMPOUND
    # ──────────────────────────────────────────────────────────────
    {
        "name": "Power Clean",
        "muscle_group": MuscleGroup.FULL_BODY,
        "secondary_muscles": ["traps", "shoulders", "quads", "glutes", "back"],
        "equipment": EquipmentType.BARBELL,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.ADVANCED,
        "instructions": "Pull bar from floor, extend explosively through hips and knees, then drop under bar and receive in a front rack position.",
        "tips": "Requires coaching. Focus on hip extension power.",
    },
    {
        "name": "Kettlebell Swing",
        "muscle_group": MuscleGroup.FULL_BODY,
        "secondary_muscles": ["glutes", "hamstrings", "core", "shoulders"],
        "equipment": EquipmentType.KETTLEBELL,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.INTERMEDIATE,
        "instructions": "Hip hinge to start swing. Drive hips forward explosively to swing the kettlebell to shoulder height. Let it swing back between legs.",
        "tips": "This is a hip hinge — not a squat. Power comes from the hips.",
    },
    {
        "name": "Kettlebell Clean and Press",
        "muscle_group": MuscleGroup.FULL_BODY,
        "secondary_muscles": ["shoulders", "back", "core"],
        "equipment": EquipmentType.KETTLEBELL,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.INTERMEDIATE,
        "instructions": "Clean kettlebell to shoulder. Press overhead. Lower and repeat.",
        "tips": "Combines pulling and pressing in one movement.",
    },
    {
        "name": "Thruster",
        "muscle_group": MuscleGroup.FULL_BODY,
        "secondary_muscles": ["quads", "shoulders", "triceps", "core"],
        "equipment": EquipmentType.BARBELL,
        "exercise_type": ExerciseType.STRENGTH,
        "difficulty": DifficultyLevel.ADVANCED,
        "instructions": "Front squat the bar, then use the momentum to press overhead in one fluid movement.",
        "tips": "Used in CrossFit. Efficient full-body conditioning.",
    },
    {
        "name": "Medicine Ball Slam",
        "muscle_group": MuscleGroup.FULL_BODY,
        "secondary_muscles": ["core", "shoulders", "lats"],
        "equipment": EquipmentType.OTHER,
        "exercise_type": ExerciseType.PLYOMETRIC,
        "difficulty": DifficultyLevel.BEGINNER,
        "instructions": "Raise medicine ball overhead, then slam it forcefully into the floor. Pick it up and repeat.",
        "tips": "Great for power and stress relief. Use a non-bounce slam ball.",
    },
]


class Command(BaseCommand):
    help = "Seeds the global exercise library with default exercises."

    def handle(self, *args, **options):
        created_count = 0
        updated_count = 0

        for data in EXERCISES:
            obj, created = Exercise.objects.get_or_create(
                name=data["name"],
                defaults={
                    "muscle_group":       data["muscle_group"],
                    "secondary_muscles":  data.get("secondary_muscles", []),
                    "equipment":          data["equipment"],
                    "exercise_type":      data["exercise_type"],
                    "difficulty":         data["difficulty"],
                    "instructions":       data.get("instructions", ""),
                    "tips":               data.get("tips", ""),
                    "is_global":          True,
                    "created_by":         None,
                },
            )

            if not created:
                # Update fields that might have improved descriptions
                updated = False
                for field in ("muscle_group", "secondary_muscles", "equipment",
                              "exercise_type", "difficulty", "instructions", "tips"):
                    if getattr(obj, field) != data.get(field):
                        setattr(obj, field, data.get(field))
                        updated = True
                if updated:
                    obj.save()
                    updated_count += 1
            else:
                created_count += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"Done. {created_count} exercises created, {updated_count} updated."
            )
        )