# Generated by Django 6.0.1 on 2026-02-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'Sedentary (little or no exercise)'), ('light', 'Light exercise (1–3 days/week)'), ('moderate', 'Moderate exercise (3–5 days/week)'), ('active', 'Very active (6–7 days/week)'), ('athlete', 'Athlete (physical job or intense training)')], default='sedentary', max_length=20),
        ),
    ]
