# Generated by Django 6.0.1 on 2026-02-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='goal',
            field=models.CharField(choices=[('loss', 'Weight Loss'), ('maintain', 'Maintain'), ('gain', 'Weight Gain')], default='maintain', max_length=10),
        ),
    ]
