# Generated by Django 5.2.10 on 2026-05-05 09:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('muscle_group', models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('biceps', 'Biceps'), ('triceps', 'Triceps'), ('forearms', 'Forearms'), ('core', 'Core'), ('quads', 'Quads'), ('hamstrings', 'Hamstrings'), ('glutes', 'Glutes'), ('calves', 'Calves'), ('full_body', 'Full Body'), ('cardio', 'Cardio')], max_length=50)),
                ('secondary_muscles', models.JSONField(blank=True, default=list)),
                ('equipment', models.CharField(choices=[('barbell', 'Barbell'), ('dumbbell', 'Dumbbell'), ('cable', 'Cable'), ('machine', 'Machine'), ('bodyweight', 'Bodyweight'), ('kettlebell', 'Kettlebell'), ('band', 'Resistance Band'), ('other', 'Other')], default='barbell', max_length=50)),
                ('exercise_type', models.CharField(choices=[('strength', 'Strength'), ('cardio', 'Cardio'), ('stretching', 'Stretching'), ('plyometric', 'Plyometric')], default='strength', max_length=50)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=50)),
                ('instructions', models.TextField(blank=True)),
                ('tips', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('is_global', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_exercises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserFitnessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_unit', models.CharField(choices=[('kg', 'Kilograms'), ('lbs', 'Pounds')], default='kg', max_length=5)),
                ('default_rest_time', models.IntegerField(default=90)),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=50)),
                ('progression_type', models.CharField(choices=[('linear', 'Linear (add weight each session)'), ('double', 'Double Progression (reps then weight)'), ('percentage', 'Percentage-based'), ('rpe', 'RPE-based')], default='double', max_length=50)),
                ('progression_increment_kg', models.FloatField(default=2.5)),
                ('progression_increment_lbs', models.FloatField(default=5.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('superset_group', models.CharField(blank=True, max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.exercise')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveIntegerField(default=1)),
                ('weight', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('reps', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('completed', models.BooleanField(default=False)),
                ('rpe', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('rest_taken', models.IntegerField(blank=True, null=True)),
                ('rest_target', models.IntegerField(default=90)),
                ('tempo', models.CharField(blank=True, max_length=20)),
                ('is_warmup', models.BooleanField(default=False)),
                ('is_dropset', models.BooleanField(default=False)),
                ('is_pr', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workout_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='workout.workoutexercise')),
            ],
            options={
                'ordering': ['set_number'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('category', models.CharField(choices=[('push', 'Push'), ('pull', 'Pull'), ('legs', 'Legs'), ('full_body', 'Full Body'), ('anterior', 'Anterior'), ('posterior', 'Posterior'), ('upper', 'Upper'), ('lower', 'Lower'), ('cardio', 'Cardio'), ('custom', 'Custom')], default='push', max_length=50)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('energy_level', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('mood_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('bodyweight', models.FloatField(blank=True, null=True)),
                ('weight_unit', models.CharField(choices=[('kg', 'Kilograms'), ('lbs', 'Pounds')], default='kg', max_length=5)),
                ('is_finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutHistorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=50)),
                ('total_volume', models.FloatField(default=0)),
                ('total_sets', models.IntegerField(default=0)),
                ('total_reps', models.IntegerField(default=0)),
                ('duration_secs', models.IntegerField(default=0)),
                ('prs_broken', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_snapshots', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot', to='workout.workoutsession')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercises', to='workout.workoutsession'),
        ),
        migrations.CreateModel(
            name='WorkoutTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('push', 'Push'), ('pull', 'Pull'), ('legs', 'Legs'), ('full_body', 'Full Body'), ('anterior', 'Anterior'), ('posterior', 'Posterior'), ('upper', 'Upper'), ('lower', 'Lower'), ('cardio', 'Cardio'), ('custom', 'Custom')], default='push', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('estimated_duration', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='workout.workouttemplate'),
        ),
        migrations.CreateModel(
            name='TemplateExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('default_sets', models.IntegerField(default=3)),
                ('default_reps', models.IntegerField(default=10)),
                ('default_weight', models.FloatField(blank=True, null=True)),
                ('default_rest', models.IntegerField(default=90)),
                ('superset_group', models.CharField(blank=True, max_length=5)),
                ('notes', models.TextField(blank=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.exercise')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_exercises', to='workout.workouttemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProgressionSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_weight', models.FloatField()),
                ('last_reps', models.IntegerField()),
                ('last_rpe', models.FloatField(blank=True, null=True)),
                ('suggested_weight', models.FloatField()),
                ('suggested_reps', models.IntegerField()),
                ('suggested_sets', models.IntegerField(default=3)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('progression_type', models.CharField(choices=[('linear', 'Linear (add weight each session)'), ('double', 'Double Progression (reps then weight)'), ('percentage', 'Percentage-based'), ('rpe', 'RPE-based')], default='double', max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('applied', models.BooleanField(default=False)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
                'unique_together': {('user', 'exercise', 'applied')},
            },
        ),
        migrations.CreateModel(
            name='PersonalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_weight', models.FloatField(default=0)),
                ('max_reps', models.IntegerField(default=0)),
                ('max_volume', models.FloatField(default=0)),
                ('max_1rm', models.FloatField(default=0)),
                ('achieved_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prs', to='workout.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prs', to=settings.AUTH_USER_MODEL)),
                ('set_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workout.set')),
            ],
            options={
                'unique_together': {('user', 'exercise')},
            },
        ),
    ]
