# Generated by Django 6.0.1 on 2026-02-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylog',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
