# Generated by Django 5.2.10 on 2026-03-12 02:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_alter_dailylog_created_at_alter_dailylog_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylog',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
