# Generated by Django 5.2.10 on 2026-02-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serving', models.CharField(blank=True, max_length=100)),
                ('calories', models.FloatField(blank=True, null=True)),
                ('water', models.FloatField(blank=True, null=True)),
                ('total_fat', models.FloatField(blank=True, null=True)),
                ('saturated_fat', models.FloatField(blank=True, null=True)),
                ('monounsaturated_fat', models.FloatField(blank=True, null=True)),
                ('polyunsaturated_fat', models.FloatField(blank=True, null=True)),
                ('cholesterol', models.FloatField(blank=True, null=True)),
                ('total_carbs', models.FloatField(blank=True, null=True)),
                ('starch', models.FloatField(blank=True, null=True)),
                ('sugars', models.FloatField(blank=True, null=True)),
                ('fiber', models.FloatField(blank=True, null=True)),
                ('protein', models.FloatField(blank=True, null=True)),
                ('vitamin_c', models.FloatField(blank=True, null=True)),
                ('vitamin_b6', models.FloatField(blank=True, null=True)),
                ('folate_b9', models.FloatField(blank=True, null=True)),
                ('vitamin_a', models.FloatField(blank=True, null=True)),
                ('thiamin_b1', models.FloatField(blank=True, null=True)),
                ('riboflavin_b2', models.FloatField(blank=True, null=True)),
                ('niacin_b3', models.FloatField(blank=True, null=True)),
                ('vitamin_e', models.FloatField(blank=True, null=True)),
                ('vitamin_k', models.FloatField(blank=True, null=True)),
                ('potassium', models.FloatField(blank=True, null=True)),
                ('magnesium', models.FloatField(blank=True, null=True)),
                ('phosphorus', models.FloatField(blank=True, null=True)),
                ('calcium', models.FloatField(blank=True, null=True)),
                ('sodium', models.FloatField(blank=True, null=True)),
                ('iron', models.FloatField(blank=True, null=True)),
                ('zinc', models.FloatField(blank=True, null=True)),
                ('copper', models.FloatField(blank=True, null=True)),
                ('manganese', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
