# Generated by Django 5.2.10 on 2026-02-09 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='folate_b9',
            new_name='trans_fat',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='niacin_b3',
            new_name='vitamin_b1',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='riboflavin_b2',
            new_name='vitamin_b12',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='thiamin_b1',
            new_name='vitamin_b2',
        ),
        migrations.AddField(
            model_name='food',
            name='vitamin_b3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='vitamin_b9',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
